In [13]:
from openbb import obb
obb.user.preferences.output_type = "dataframe"

obb.equity.price.historical("SPY",provider="yfinance",start_date="2024-10-03",interval="60m")

,open,high,low,close,volume,split_ratio,dividend,capital_gains
date,,,,,,,,
2024-10-03 09:30:00,567.359985,569.802490,566.770020,567.169922,8994309,0.0,0.0,0.0
2024-10-03 10:30:00,566.599976,568.489990,566.239990,567.474915,4517151,0.0,0.0,0.0
2024-10-03 11:30:00,567.440002,569.159973,567.440002,568.700012,2230945,0.0,0.0,0.0
2024-10-03 12:30:00,568.708130,568.710022,565.489990,566.469971,6161439,0.0,0.0,0.0
2024-10-03 13:30:00,566.460022,567.419983,566.050110,567.010010,4699261,0.0,0.0,0.0
2024-10-03 14:30:00,566.989990,567.250000,566.049988,566.530029,3649827,0.0,0.0,0.0
2024-10-03 15:30:00,566.549988,568.270020,566.440002,567.780029,6404739,0.0,0.0,0.0
2024-10-04 09:30:00,572.349976,572.710022,568.349976,568.830017,12086389,0.0,0.0,0.0
2024-10-04 10:30:00,568.840027,570.729980,568.159973,568.780029,5098431,0.0,0.0,0.0
2024-10-04 11:30:00,568.780029,570.780029,568.280029,569.804993,3217281,0.0,0.0,0.0

In [14]:
obb.equity.fundamental.metrics("AAPL,MSFT",provider="yfinance")

,symbol,market_cap,pe_ratio,forward_pe,peg_ratio,peg_ratio_ttm,enterprise_to_ebitda,earnings_growth,earnings_growth_quarterly,revenue_per_share,...,price_to_book,enterprise_value,overall_risk,audit_risk,board_risk,compensation_risk,shareholder_rights_risk,beta,price_return_1y,currency
0,AAPL,3.448290e+12,34.520546,30.320856,3.04,2.1658,26.336,0.111,0.079,24.957,...,51.75719,3470620622848,1.0,6.0,1.0,2.0,1.0,1.239,0.271452,USD
1,MSFT,3.092591e+12,35.289227,27.336400,2.18,2.2513,24.093,0.097,0.097,32.986,...,11.52042,3118478917632,1.0,3.0,4.0,2.0,2.0,0.896,0.272811,USD

In [15]:
obb.equity.compare.groups(group="industry",metric="valuation",provider="finviz")

,name,market_cap,performance_1d,forward_pe,eps_growth_past_5y,eps_growth_next_5y,volume,price_to_sales,price_to_book,price_to_cash,price_to_free_cash_flow,sales_growth_past_5_years,pe,peg
0,Pharmaceutical Retailers,7820000000,0.0059,5.03,-0.0562,0.0420,17200000,0.05,0.56,9.51,411.11,0.0386,NaN,NaN
1,Insurance - Reinsurance,51730000000,0.0260,7.31,0.5568,0.0739,1930000,0.97,1.33,NaN,2.90,0.2214,7.12,0.96
2,REIT - Mortgage,58200000000,-0.0001,7.41,-0.2222,0.0310,58370000,1.83,0.88,4.14,6.70,0.3555,24.16,7.78
3,Coking Coal,10290000000,0.0268,7.78,0.0579,0.0624,1790000,0.97,1.67,7.12,9.72,0.1563,8.38,1.34
4,Marine Shipping,39150000000,-0.0108,8.22,0.2136,0.0990,29380000,1.30,1.11,6.17,9.22,0.2488,6.15,0.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,REIT - Office,76300000000,0.0028,56.06,-0.2135,0.0072,20430000,3.91,1.10,8.71,13.86,0.0650,88.54,123.11
141,REIT - Healthcare Facilities,161470000000,-0.0063,65.54,-0.1286,0.3643,24730000,6.98,2.08,29.93,28.13,0.1160,111.28,3.05
142,Shell Companies,27390000000,-0.0003,138.76,NaN,NaN,3350000,26.26,2.39,41.03,109.65,0.6205,58.59,NaN
143,Infrastructure Operations,33760000000,-0.0238,146.75,NaN,0.1425,1220000,3.23,7.48,8.32,32.60,0.0814,37.51,2.63
144,Real Estate - Diversified,7590000000,0.0085,147.98,0.1840,0.1971,356330,4.83,1.94,7.41,72.41,0.2110,95.72,4.86

In [17]:
obb.equity.compare.groups(group="technology",metric="performance",provider="finviz").sort_values(by="volume", ascending=False)

,name,performance_1d,performance_1w,performance_1m,performance_3m,performance_6m,performance_1y,performance_ytd,analyst_recommendation,volume,volume_average,volume_relative
10,Semiconductors,0.0169,0.0154,0.1343,-0.0508,0.2456,1.0390,0.6886,1.47,479400000,658050000,0.73
2,Software - Infrastructure,0.0063,-0.0153,0.0351,-0.0588,0.0210,0.3124,0.1189,1.54,283170000,319670000,0.89
8,Software - Application,0.0178,0.0089,0.0771,0.0704,0.0271,0.3042,0.0792,1.82,265160000,367430000,0.72
7,Communication Equipment,0.0073,-0.0015,0.0711,0.1569,0.2009,0.2011,0.1839,2.31,85550000,135800000,0.63
9,Computer Hardware,0.0157,0.0111,0.1141,-0.1149,0.0007,0.6715,0.4265,1.95,84710000,143050000,0.59
0,Solar,-0.0027,-0.0765,0.0233,-0.0005,-0.0794,-0.2469,-0.2671,1.82,81280000,163260000,0.50
11,Information Technology Services,0.0093,0.0204,0.0574,0.1829,0.1374,0.3375,0.1703,2.16,66660000,85400000,0.78
1,Electronic Components,0.0109,-0.0195,0.0466,-0.0168,0.0969,0.3011,0.1922,1.92,64080000,84520000,0.76
6,Consumer Electronics,0.0056,-0.0058,0.0177,0.0083,0.2995,0.2819,0.1482,1.83,44960000,70850000,0.63
3,Semiconductor Equipment & Materials,0.0078,-0.0109,0.0703,-0.2029,-0.0808,0.4029,0.1383,1.75,34690000,40640000,0.85
4,Scientific & Technical Instruments,0.0085,-0.0083,0.0433,0.0629,0.0473,0.2664,0.1261,2.16,16800000,25300000,0.66
5,Electronics & Computer Distribution,0.0184,-0.0069,0.0414,0.0867,0.0673,0.2393,0.1195,2.57,1420000,2270000,0.63

In [18]:
obb.equity.compare.groups(group="sector",metric="overview",provider="finviz").sort_values(by="dividend_yield", ascending=False)

,name,market_cap,performance_1d,dividend_yield,pe,forward_pe,peg,float_short,volume,Stocks
6,Energy,3628390000000,0.0090,0.0443,12.20,11.29,1.89,0.0303,594350000,252
0,Real Estate,1696850000000,-0.0047,0.0361,40.08,32.46,4.15,0.0459,318930000,267
1,Utilities,1654680000000,0.0013,0.0290,22.01,16.81,2.78,0.0212,175390000,113
3,Consumer Defensive,4118689999999,0.0032,0.0239,26.53,19.76,3.21,0.0175,328040000,245
4,Basic Materials,2143120000000,0.0037,0.0220,24.41,15.28,2.75,0.0208,401650000,272
10,Financial,11566410000000,0.0177,0.0202,16.70,14.23,1.54,0.0127,1030000000,936
2,Healthcare,8381010000000,0.0025,0.0148,38.76,19.12,2.28,0.0456,935220000,1183
5,Industrials,5756960000000,0.0068,0.0134,26.37,20.45,2.37,0.0434,770490000,659
9,Consumer Cyclical,7865230000000,0.0169,0.0089,24.73,19.84,1.50,0.0472,1730000000,573
7,Communication Services,8133600000000,0.0100,0.0084,25.11,18.59,1.43,0.0236,415290000,258
8,Technology,20941910000000,0.0112,0.0067,42.32,25.53,2.08,0.0270,1510000000,787